name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - 'stable'
        - 'oldstable'
    steps:
    - name: Checkout the repo
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go }}'
        check-latest: true
        cache-dependency-path: ./go.sum

    - name: Build
      run: go build -v ./...

    - name: Test
      run: ./test.sh
