name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.22'
        - 'tip'
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      if: matrix.go != 'tip'
      uses: actions/setup-go@v4
      with:
        go-version: '${{ matrix.go }}'
        check-latest: true

    - name: Install Go
      if: matrix.go == 'tip'
      run: |
        curl -sL https://storage.googleapis.com/go-build-snap/go/linux-amd64/$(git ls-remote https://github.com/golang/go.git HEAD | awk '{print $1;}').tar.gz -o gotip.tar.gz
        ls -lah gotip.tar.gz
        mkdir -p ~/sdk/gotip
        tar -C ~/sdk/gotip -xzf gotip.tar.gz
        ~/sdk/gotip/bin/go version
        echo "PATH=$HOME/go/bin:$HOME/sdk/gotip/bin/:$PATH" >> $GITHUB_ENV

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
