name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go:
        - '1.22'
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '${{ matrix.go }}'
        check-latest: true

    - name: Build
      run: go build -v ./...

    - name: Test
      run: ./test.sh
